In [1]:
import pandas as pd
import os
os.environ['KAGGLE_USERNAME']='dinesh223344'
os.environ['KAGGLE_KEY']='KGAT_4f293546a7b4700c41008b912382b767'

In [2]:
!kaggle datasets download -d 'stealthtechnologies/employee-attrition-dataset'

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/stealthtechnologies/employee-attrition-dataset
License(s): apache-2.0
Downloading employee-attrition-dataset.zip to /content
100% 1.72M/1.72M [00:00<00:00, 80.7MB/s]

In [3]:
!unzip /content/employee-attrition-dataset.zip

Archive:  /content/employee-attrition-dataset.zip
  inflating: test.csv
  inflating: train.csv

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("/content/train.csv")

In [6]:
df.head()

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure,Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
0,8410,31,Male,19,Education,5390,Excellent,Medium,Average,2,...,0,Mid,Medium,89,No,No,No,Excellent,Medium,Stayed
1,64756,59,Female,4,Media,5534,Poor,High,Low,3,...,3,Mid,Medium,21,No,No,No,Fair,Low,Stayed
2,30257,24,Female,10,Healthcare,8159,Good,High,Low,0,...,3,Mid,Medium,74,No,No,No,Poor,Low,Stayed
3,65791,36,Female,7,Education,3989,Good,High,High,1,...,2,Mid,Small,50,Yes,No,No,Good,Medium,Stayed
4,65026,56,Male,41,Education,4821,Fair,Very High,Average,0,...,0,Senior,Medium,68,No,No,No,Fair,Medium,Stayed

In [7]:
df.tail()

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure,Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
59593,37195,50,Female,12,Education,4414,Fair,High,Average,1,...,2,Senior,Small,35,No,No,Yes,Poor,Very High,Left
59594,6266,18,Male,4,Healthcare,8040,Fair,High,High,3,...,0,Senior,Medium,73,No,No,No,Fair,Medium,Left
59595,54887,22,Female,14,Technology,7944,Fair,High,High,0,...,2,Entry,Small,29,No,Yes,No,Good,Medium,Stayed
59596,861,23,Male,8,Education,2931,Fair,Very High,Average,0,...,0,Entry,Large,9,No,No,No,Good,Low,Left
59597,15796,56,Male,19,Technology,6660,Good,High,Average,0,...,3,Mid,Medium,81,No,No,No,Good,Low,Stayed

In [8]:
df.describe()

,Employee ID,Age,Years at Company,Monthly Income,Number of Promotions,Distance from Home,Number of Dependents,Company Tenure
count,59598.000000,59598.000000,59598.000000,59598.000000,59598.000000,59598.000000,59598.000000,59598.000000
mean,37227.118729,38.565875,15.753901,7302.397983,0.832578,50.007651,1.648075,55.758415
std,21519.150028,12.079673,11.245981,2151.457423,0.994991,28.466459,1.555689,25.411090
min,1.000000,18.000000,1.000000,1316.000000,0.000000,1.000000,0.000000,2.000000
25%,18580.250000,28.000000,7.000000,5658.000000,0.000000,25.000000,0.000000,36.000000
50%,37209.500000,39.000000,13.000000,7354.000000,1.000000,50.000000,1.000000,56.000000
75%,55876.750000,49.000000,23.000000,8880.000000,2.000000,75.000000,3.000000,76.000000
max,74498.000000,59.000000,51.000000,16149.000000,4.000000,99.000000,6.000000,128.000000

In [9]:
df.isnull().sum()

Employee ID                 0
Age                         0
Gender                      0
Years at Company            0
Job Role                    0
Monthly Income              0
Work-Life Balance           0
Job Satisfaction            0
Performance Rating          0
Number of Promotions        0
Overtime                    0
Distance from Home          0
Education Level             0
Marital Status              0
Number of Dependents        0
Job Level                   0
Company Size                0
Company Tenure              0
Remote Work                 0
Leadership Opportunities    0
Innovation Opportunities    0
Company Reputation          0
Employee Recognition        0
Attrition                   0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
df["Age_group"]=pd.cut(
    df["Age"],
    bins=[0,19,30,60,100],labels=["teen","adult","old","too old"])

In [13]:
le = LabelEncoder()
categorical_cols = ['Age_group','Gender','Job Role','Work-Life Balance','Job Satisfaction','Performance Rating','Overtime','Education Level','Marital Status','Job Level','Company Size','Remote Work','Leadership Opportunities','Innovation Opportunities','Company Reputation','Employee Recognition','Attrition']

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])
    print(f"Column '{col}' encoded successfully.")

display(df.head())

Column 'Age_group' encoded successfully.
Column 'Gender' encoded successfully.
Column 'Job Role' encoded successfully.
Column 'Work-Life Balance' encoded successfully.
Column 'Job Satisfaction' encoded successfully.
Column 'Performance Rating' encoded successfully.
Column 'Overtime' encoded successfully.
Column 'Education Level' encoded successfully.
Column 'Marital Status' encoded successfully.
Column 'Job Level' encoded successfully.
Column 'Company Size' encoded successfully.
Column 'Remote Work' encoded successfully.
Column 'Leadership Opportunities' encoded successfully.
Column 'Innovation Opportunities' encoded successfully.
Column 'Company Reputation' encoded successfully.
Column 'Employee Recognition' encoded successfully.
Column 'Attrition' encoded successfully.

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Job Level,Company Size,Company Tenure,Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition,Age_group
0,8410,31,1,19,0,5390,0,2,0,2,...,1,1,89,0,0,0,0,2,1,1
1,64756,59,0,4,3,5534,3,0,3,3,...,1,1,21,0,0,0,1,1,1,1
2,30257,24,0,10,2,8159,2,0,3,0,...,1,1,74,0,0,0,3,1,1,0
3,65791,36,0,7,0,3989,2,0,2,1,...,1,2,50,1,0,0,2,2,1,1
4,65026,56,1,41,0,4821,1,3,0,0,...,2,1,68,0,0,0,1,2,1,1

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59598 entries, 0 to 59597
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Employee ID               59598 non-null  int64
 1   Age                       59598 non-null  int64
 2   Gender                    59598 non-null  int64
 3   Years at Company          59598 non-null  int64
 4   Job Role                  59598 non-null  int64
 5   Monthly Income            59598 non-null  int64
 6   Work-Life Balance         59598 non-null  int64
 7   Job Satisfaction          59598 non-null  int64
 8   Performance Rating        59598 non-null  int64
 9   Number of Promotions      59598 non-null  int64
 10  Overtime                  59598 non-null  int64
 11  Distance from Home        59598 non-null  int64
 12  Education Level           59598 non-null  int64
 13  Marital Status            59598 non-null  int64
 14  Number of Dependents      59598 non-null  int64
 15  Job Level                 59598 non-null  int64
 16  Company Size              59598 non-null  int64
 17  Company Tenure            59598 non-null  int64
 18  Remote Work               59598 non-null  int64
 19  Leadership Opportunities  59598 non-null  int64
 20  Innovation Opportunities  59598 non-null  int64
 21  Company Reputation        59598 non-null  int64
 22  Employee Recognition      59598 non-null  int64
 23  Attrition                 59598 non-null  int64
 24  Age_group                 59598 non-null  int64
dtypes: int64(25)
memory usage: 11.4 MB

In [15]:
for col in df:
  Q1=df[col].quantile(0.25)
  Q3=df[col].quantile(0.75)

  IQR = Q3-Q1
  lower=Q1 - 1.5 *IQR
  upper=Q3 + 1.5 *IQR

  outliers =df[(df[col]<lower) | (df[col] > upper)]

  print(f"{col} : {len(outliers)} outliers")

Employee ID : 0 outliers
Age : 0 outliers
Gender : 0 outliers
Years at Company : 273 outliers
Job Role : 0 outliers
Monthly Income : 50 outliers
Work-Life Balance : 0 outliers
Job Satisfaction : 0 outliers
Performance Rating : 2950 outliers
Number of Promotions : 0 outliers
Overtime : 0 outliers
Distance from Home : 0 outliers
Education Level : 0 outliers
Marital Status : 0 outliers
Number of Dependents : 0 outliers
Job Level : 0 outliers
Company Size : 0 outliers
Company Tenure : 0 outliers
Remote Work : 11359 outliers
Leadership Opportunities : 2918 outliers
Innovation Opportunities : 9703 outliers
Company Reputation : 0 outliers
Employee Recognition : 0 outliers
Attrition : 0 outliers
Age_group : 0 outliers

In [16]:
df.drop("Employee ID",axis=1,inplace=True)

In [17]:
x=df.drop(['Attrition'],axis=1)
y=df['Attrition']

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [19]:
x = pd.get_dummies(x,drop_first=True)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=82)
X_train=scaler.fit_transform(x_train)
X_test=scaler.transform(x_test)
x.head()

,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,Overtime,...,Number of Dependents,Job Level,Company Size,Company Tenure,Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Age_group
0,31,1,19,0,5390,0,2,0,2,0,...,0,1,1,89,0,0,0,0,2,1
1,59,0,4,3,5534,3,0,3,3,0,...,3,1,1,21,0,0,0,1,1,1
2,24,0,10,2,8159,2,0,3,0,0,...,3,1,1,74,0,0,0,3,1,0
3,36,0,7,0,3989,2,0,2,1,0,...,2,1,2,50,1,0,0,2,2,1
4,56,1,41,0,4821,1,3,0,0,1,...,0,2,1,68,0,0,0,1,2,1

In [20]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [21]:
model=DecisionTreeClassifier()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
accuracy_score(y_test,y_pred)

0.6604026845637584

In [22]:
model.score(X_test,y_test)

0.6604026845637584

In [23]:
from sklearn.ensemble import RandomForestClassifier
model1=RandomForestClassifier()
model1.fit(X_train,y_train)

RandomForestClassifier()

In [24]:
accuracy_score(y_test,y_pred)

0.6604026845637584

In [25]:
model1.score(X_test,y_test)

0.7416107382550335

In [27]:
from sklearn.ensemble import GradientBoostingClassifier
mode=GradientBoostingClassifier(learning_rate=0.1,max_depth=3,n_estimators=100,random_state=42)
mode.fit(X_train,y_train)

GradientBoostingClassifier(random_state=42)

In [28]:
y_pred=mode.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

Accuracy: 0.7550335570469798

In [29]:
from sklearn.ensemble import AdaBoostClassifier
model1=AdaBoostClassifier(random_state=42,learning_rate=0.1,n_estimators=100)
model1.fit(X_train,y_train)

AdaBoostClassifier(learning_rate=0.1, n_estimators=100, random_state=42)

In [30]:
y_pred=model1.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

Accuracy: 0.7071728187919463

In [31]:
from xgboost import XGBClassifier
model2=XGBClassifier(random_state=42,learning_rate=0.1,n_estimators=100)
model2.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [32]:
y_pred=model2.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

Accuracy: 0.7567114093959731

In [33]:
from lightgbm import LGBMClassifier
model3=LGBMClassifier(n_estimators=100,random_state=42)
model3.fit(X_train,y_train)

[LightGBM] [Info] Number of positive: 18729, number of negative: 17029
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006767 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 658
[LightGBM] [Info] Number of data points in the train set: 35758, number of used features: 23
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.523771 -> initscore=0.095155
[LightGBM] [Info] Start training from score 0.095155

LGBMClassifier(random_state=42)

In [34]:
y_pred=model3.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

Accuracy: 0.7560822147651006

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [35]:
!pip install catboost
from catboost import CatBoostClassifier

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 6.8 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [36]:
model4=CatBoostClassifier(n_estimators=100,max_depth=3,random_state=42)
model4.fit(X_train,y_train)

Learning rate set to 0.391944
0:	learn: 0.6151654	total: 104ms	remaining: 10.3s
1:	learn: 0.5854544	total: 135ms	remaining: 6.6s
2:	learn: 0.5701912	total: 148ms	remaining: 4.78s
3:	learn: 0.5574969	total: 161ms	remaining: 3.87s
4:	learn: 0.5449092	total: 195ms	remaining: 3.7s
5:	learn: 0.5348008	total: 234ms	remaining: 3.66s
6:	learn: 0.5277078	total: 271ms	remaining: 3.6s
7:	learn: 0.5227862	total: 316ms	remaining: 3.63s
8:	learn: 0.5173141	total: 345ms	remaining: 3.48s
9:	learn: 0.5132414	total: 357ms	remaining: 3.21s
10:	learn: 0.5080747	total: 368ms	remaining: 2.98s
11:	learn: 0.5045238	total: 379ms	remaining: 2.78s
12:	learn: 0.5017636	total: 391ms	remaining: 2.62s
13:	learn: 0.4993006	total: 403ms	remaining: 2.47s
14:	learn: 0.4965961	total: 417ms	remaining: 2.36s
15:	learn: 0.4943256	total: 427ms	remaining: 2.24s
16:	learn: 0.4923589	total: 438ms	remaining: 2.14s
17:	learn: 0.4901940	total: 449ms	remaining: 2.05s
18:	learn: 0.4887616	total: 461ms	remaining: 1.96s
19:	learn: 0.4872867	total: 475ms	remaining: 1.9s
20:	learn: 0.4862575	total: 498ms	remaining: 1.87s
21:	learn: 0.4850412	total: 511ms	remaining: 1.81s
22:	learn: 0.4840362	total: 523ms	remaining: 1.75s
23:	learn: 0.4831387	total: 547ms	remaining: 1.73s
24:	learn: 0.4819559	total: 574ms	remaining: 1.72s
25:	learn: 0.4807869	total: 586ms	remaining: 1.67s
26:	learn: 0.4797845	total: 598ms	remaining: 1.61s
27:	learn: 0.4789732	total: 612ms	remaining: 1.57s
28:	learn: 0.4782775	total: 624ms	remaining: 1.53s
29:	learn: 0.4772676	total: 635ms	remaining: 1.48s
30:	learn: 0.4766011	total: 646ms	remaining: 1.44s
31:	learn: 0.4759245	total: 658ms	remaining: 1.4s
32:	learn: 0.4753968	total: 669ms	remaining: 1.36s
33:	learn: 0.4747630	total: 682ms	remaining: 1.32s
34:	learn: 0.4743086	total: 696ms	remaining: 1.29s
35:	learn: 0.4738329	total: 708ms	remaining: 1.26s
36:	learn: 0.4734250	total: 732ms	remaining: 1.25s
37:	learn: 0.4729847	total: 755ms	remaining: 1.23s
38:	learn: 0.4725039	total: 776ms	remaining: 1.21s
39:	learn: 0.4720355	total: 796ms	remaining: 1.19s
40:	learn: 0.4716993	total: 822ms	remaining: 1.18s
41:	learn: 0.4713669	total: 846ms	remaining: 1.17s
42:	learn: 0.4710616	total: 867ms	remaining: 1.15s
43:	learn: 0.4707858	total: 882ms	remaining: 1.12s
44:	learn: 0.4704786	total: 894ms	remaining: 1.09s
45:	learn: 0.4701736	total: 908ms	remaining: 1.06s
46:	learn: 0.4698866	total: 921ms	remaining: 1.04s
47:	learn: 0.4696488	total: 932ms	remaining: 1.01s
48:	learn: 0.4692535	total: 944ms	remaining: 983ms
49:	learn: 0.4689309	total: 957ms	remaining: 957ms
50:	learn: 0.4686875	total: 995ms	remaining: 956ms
51:	learn: 0.4684088	total: 1.03s	remaining: 956ms
52:	learn: 0.4681371	total: 1.07s	remaining: 946ms
53:	learn: 0.4678515	total: 1.1s	remaining: 939ms
54:	learn: 0.4676583	total: 1.13s	remaining: 925ms
55:	learn: 0.4674729	total: 1.15s	remaining: 904ms
56:	learn: 0.4672098	total: 1.17s	remaining: 884ms
57:	learn: 0.4669217	total: 1.2s	remaining: 872ms
58:	learn: 0.4667133	total: 1.24s	remaining: 859ms
59:	learn: 0.4664548	total: 1.28s	remaining: 853ms
60:	learn: 0.4662746	total: 1.32s	remaining: 843ms
61:	learn: 0.4660969	total: 1.36s	remaining: 835ms
62:	learn: 0.4659128	total: 1.4s	remaining: 821ms
63:	learn: 0.4657544	total: 1.44s	remaining: 808ms
64:	learn: 0.4655990	total: 1.47s	remaining: 794ms
65:	learn: 0.4653906	total: 1.51s	remaining: 778ms
66:	learn: 0.4651571	total: 1.54s	remaining: 759ms
67:	learn: 0.4650097	total: 1.58s	remaining: 744ms
68:	learn: 0.4648435	total: 1.63s	remaining: 732ms
69:	learn: 0.4646404	total: 1.66s	remaining: 710ms
70:	learn: 0.4644783	total: 1.68s	remaining: 687ms
71:	learn: 0.4642700	total: 1.71s	remaining: 665ms
72:	learn: 0.4640532	total: 1.74s	remaining: 643ms
73:	learn: 0.4638464	total: 1.75s	remaining: 615ms
74:	learn: 0.4636280	total: 1.76s	remaining: 587ms
75:	learn: 0.4634787	total: 1.77s	remaining: 559ms
76:	learn: 0.4633562	total: 1.78s	remaining: 532ms
77:	learn: 0.4631816	total: 1.79s	remaining: 505ms
78:	learn: 0.4630327	total: 1.8s	remaining: 479ms
79:	learn: 0.4628146	total: 1.82s	remaining: 456ms
80:	learn: 0.4626233	total: 1.85s	remaining: 434ms
81:	learn: 0.4625143	total: 1.86s	remaining: 409ms
82:	learn: 0.4623644	total: 1.88s	remaining: 384ms
83:	learn: 0.4621910	total: 1.9s	remaining: 362ms
84:	learn: 0.4620232	total: 1.91s	remaining: 337ms
85:	learn: 0.4618653	total: 1.93s	remaining: 314ms
86:	learn: 0.4617486	total: 1.94s	remaining: 290ms
87:	learn: 0.4616226	total: 1.96s	remaining: 267ms
88:	learn: 0.4614569	total: 1.97s	remaining: 244ms
89:	learn: 0.4613154	total: 1.98s	remaining: 220ms
90:	learn: 0.4611691	total: 1.99s	remaining: 197ms
91:	learn: 0.4610552	total: 2s	remaining: 174ms
92:	learn: 0.4609101	total: 2.01s	remaining: 151ms
93:	learn: 0.4607746	total: 2.02s	remaining: 129ms
94:	learn: 0.4606116	total: 2.04s	remaining: 107ms
95:	learn: 0.4604637	total: 2.05s	remaining: 85.3ms
96:	learn: 0.4603038	total: 2.06s	remaining: 63.7ms
97:	learn: 0.4601780	total: 2.07s	remaining: 42.3ms
98:	learn: 0.4600063	total: 2.09s	remaining: 21.1ms
99:	learn: 0.4598263	total: 2.1s	remaining: 0us

CatBoostClassifier(max_depth=3, n_estimators=100, random_state=42)

In [37]:
y_pred=model4.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

Accuracy: 0.7598154362416107

In [39]:
from sklearn.model_selection import GridSearchCV
from catboost import CatBoostClassifier


param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.05, 0.1]
}

cat_model = CatBoostClassifier(random_state=42, verbose=0)
grid_search = GridSearchCV(estimator=cat_model, param_grid=param_grid,
                           cv=3, n_jobs=-1, verbose=2, scoring='accuracy')


grid_search.fit(X_train, y_train)


print(f"Best parameters found: {grid_search.best_params_}")
print(f"Best accuracy found: {grid_search.best_score_}")


best_cat_model = grid_search.best_estimator_
y_pred_tuned = best_cat_model.predict(X_test)
accuracy_tuned = accuracy_score(y_test, y_pred_tuned)
print(f"Test accuracy with best CatBoost model: {accuracy_tuned}")

Fitting 3 folds for each of 27 candidates, totalling 81 fits
Best parameters found: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200}
Best accuracy found: 0.7576486713166221
Test accuracy with best CatBoost model: 0.7586409395973155

In [40]:
import pickle

filename = 'best_catboost_model.pkl'
pickle.dump(best_cat_model, open(filename, 'wb'))

print(f"Best CatBoost model saved to {filename}")

Best CatBoost model saved to best_catboost_model.pkl